service:
  name: slack-clerk

plugins:
  - serverless-webpack
  - serverless-offline
provider:
  name: aws
  runtime: nodejs6.10

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
